---
- name: Setup system
  hosts: "{{ target_hosts | default('tag_class_runner') }}"
  tags:
    - system
  become: true
  tasks:
    - name: Configure OS
      ansible.builtin.include_role:
        name: os

    - name: Create Runner Group
      ansible.builtin.group:
        name: "{{ actions_runner_user }}"
        gid: 1000
        state: present

    - name: Create Runner User
      ansible.builtin.user:
        name: "{{ actions_runner_user }}"
        group: "{{ actions_runner_group }}"
        uid: 1000
        comment: "GitHub Actions Runner"
        shell: /bin/bash
        home: /__w
        createhome: true

# - name: Partition Data Volumes
#   hosts: "{{ target_hosts | default('tag_class_runner') }}"
#   tags:
#     - launch
#     - partition
#   become: true
#   tasks:
#     - name: Partition First Data Volume
#       when: data_volumes_present
#       community.general.parted:
#         device: "/dev/{{ (data_volumes | list)[0] }}"
#         number: 1
#         state: present
#         fs_type: ext4
#         label: gpt

#     - name: Format First Data Volume
#       when: data_volumes_present
#       community.general.filesystem:
#         dev: "/dev/{{ (data_volumes | list)[0] }}p1"
#         state: present
#         fstype: ext4
#         opts: -L WORK

#     - name: Mount First Data Volume
#       when: data_volumes_present
#       ansible.posix.mount:
#         src: LABEL=WORK
#         path: /mnt
#         fstype: ext4
#         boot: true
#         state: mounted

#     - name: Regather Facts
#       when: data_volumes_present
#       ansible.builtin.setup:

- name: Install Dependencies
  hosts: "{{ target_hosts | default('tag_class_runner') }}"
  tags:
    - deps
  become: true
  tasks:
    - name: Install AWS CLI
      ansible.builtin.include_role:
        name: aws_cli

    - name: Install HashiCorp Tools
      ansible.builtin.include_role:
        name: hashicorp

    - name: Install Go
      ansible.builtin.include_role:
        name: go

    - name: Install NVM
      ansible.builtin.include_role:
        name: nvm

- name: Setup Actions Runner
  hosts: "{{ target_hosts | default('tag_class_runner') }}"
  tags:
    - actions-runner
  become: true
  tasks:
    - name: Install Container Tools
      tags:
        - launch
      ansible.builtin.include_role:
        name: containers

    - name: Install GitHub Actions Runner
      tags:
        - launch
      ansible.builtin.include_role:
        name: actions_runner
